
(defun c:ctp (/ ssl sso ssn en eg typ)
  (prompt "\nSelect entities to convert to polyline: ")
  (command "select" "au" pause)
  (setq
    sso (ssget "P")
    pw (getreal "\nPolyline width: <10>: ")
    pw (if pw pw 10.0)
    ssn (ssadd)
  )
  (if sso
    (progn
      (setq ssl (sslength sso))
      (while (> (setq ssl (1- ssl)) -1)
        (setq
          en (ssname sso ssl)
          eg (entget en)
          typ (cdr (assoc 0 eg))
        )
        (cond
          ((= typ "LINE")
            (command "pedit" en "Y" "")
            (setq ssn (ssadd (entlast) ssn))
          )
          ((= typ "ARC")
            (command "pedit" en "Y" "")
            (setq ssn (ssadd (entlast) ssn))
          )
          ((= typ "PLINE")
            (setq ssn (ssadd (ssname sso ssl) ssn))
          )
          (1 (setq sso (ssdel en sso)))
        )
      )
      (setq ssl (sslength ssn))
      (command "pedit" (ssname ssn 0) "J")
      (while (> (setq ssl (1- ssl)) -1)
        (command (ssname ssn ssl))
      )
    )
  )
  (command "" "W" pw "X")
  (princ)
)
